spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe   # DB 주소 (SID = xe 기준)
    username: system
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update   # 자동으로 테이블 생성/업데이트
    show-sql: true       # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true
